version: '3.2'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  posgre:
    image: postgres:latest
    environment: 
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: kuasaipasswd
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  postgres-data:
